# Generated by Django 3.2 on 2024-10-31 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citasMedicasApp', '0004_cita_doctor'),
        ('pacientesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='cita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='citasMedicasApp.cita'),
        ),
    ]
