# Generated by Django 3.2 on 2024-10-31 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientesApp', '0002_pacientes_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='cita',
        ),
    ]
