# Generated by Django 3.2 on 2024-10-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citasMedicasApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Pacientes',
        ),
    ]
