# Generated by Django 3.2 on 2024-10-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasMedicasApp', '0002_auto_20241030_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='horaCita',
            field=models.TimeField(),
        ),
    ]
