# Generated by Django 3.2 on 2024-10-31 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctoresApp', '0001_initial'),
        ('citasMedicasApp', '0003_alter_cita_horacita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctoresApp.doctor'),
        ),
    ]
