# Generated by Django 3.2 on 2024-10-31 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientesApp', '0003_remove_pacientes_cita'),
        ('citasMedicasApp', '0004_cita_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='pacinete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientesApp.pacientes'),
        ),
    ]
