# Generated by Django 3.2 on 2024-10-31 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citasMedicasApp', '0005_cita_pacinete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='pacinete',
            new_name='paciente',
        ),
    ]
